OCAMLMAKEFILE=OCamlMakefile

SOURCES = events.ml thread_state.ml dispatch.ml server.ml
PACKS = unix json-wheel lwt cohttp cohttpserver
RESULT = server
ANNOTATE = yes
DEBUG = yes

-include $(OCAMLMAKEFILE)